### PR TITLE
Update manager

### PR DESCRIPTION
**Pull request by cthoyt**
@ddomingof do you think we should completely merge this repo into the base bio2bel repo so we don't have to update so many things out of sync?

### CODE REVIEW

**Comment by ddomingof** [comment]
Good idea, let's start making a monolith :P

**Comment by ddomingof** [comment]
I am serious though haha

**Comment by cthoyt** [comment]
haha okay

**Comment by cthoyt** [comment]
i heard microservices are so 2019 anyway

**Pull request merged**
